spring.application.name=order-system
spring.profiles.include=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 낙관적 락 버전 추가로 인한 코드
spring.jpa.hibernate.ddl-auto=update