spring.application.name=order-system
spring.profiles.include=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 테스트용
#spring.jpa.hibernate.ddl-auto=update